definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request

workflows:
  auralkit:
    name: AuralKit Workflow
    environment:
      xcode: edge
      vars:
        XCODE_SCHEME: "AuralKit"
        APP_ID: "AuralKit"
    when:
      changeset:
        includes:
          - "Sources"
          - "Tests"
          - "Aural"
          - "Package.swift"
    triggering:
      <<: *events
    scripts:
      - name: Download Metal Toolchain
        script: |
          xcodebuild -downloadComponent MetalToolchain
      - name: Build Swift Package
        script: |
          swift build
      - name: Build Aural App
        script: |
          xcodebuild -scheme Aural -configuration Debug -destination "platform=iOS Simulator,name=iPhone 17 Pro" build
