name: Aural
options:
  bundleIdPrefix: com.auralkit
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"

packages:
  AuralKit:
    path: .

targets:
  Aural:
    type: application
    platform: iOS

    sources:
      - Aural

    dependencies:
      - package: AuralKit
        product: AuralKit

    settings:
      base:
        SWIFT_VERSION: "6.2"
        PRODUCT_NAME: Aural
        PRODUCT_BUNDLE_IDENTIFIER: com.auralkit.aural
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "This app needs microphone access to transcribe speech."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "This app needs speech recognition to convert your speech to text."

