name: AuralKitDemo

options:
  bundleIdPrefix: com.auralkit
  deploymentTarget:
    iOS: 17.0
    macOS: 14.0

packages:
  AuralKit:
    path: ..

targets:
  AuralKitDemo-iOS:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Sources
        excludes:
          - "**/*macOS*"
    dependencies:
      - package: AuralKit
    info:
      path: iOS-Info.plist
      properties:
        CFBundleName: AuralKit Demo
        CFBundleDisplayName: AuralKit Demo
        CFBundleIdentifier: com.auralkit.demo.ios
        CFBundleVersion: "1.0.0"
        CFBundleShortVersionString: "1.0.0"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "AuralKit Demo needs microphone access to demonstrate speech-to-text transcription features. Your audio is processed locally on device and not transmitted anywhere."
        NSSpeechRecognitionUsageDescription: "AuralKit Demo uses speech recognition to convert your spoken words into text. This helps demonstrate the framework's capabilities for speech-to-text applications."
        UIRequiredDeviceCapabilities:
          - microphone
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.auralkit.demo.ios
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: true

  AuralKitDemo-macOS:
    type: application
    platform: macOS
    deploymentTarget: 14.0
    sources:
      - path: Sources
        excludes:
          - "**/*iOS*"
    dependencies:
      - package: AuralKit
    info:
      path: macOS-Info.plist
      properties:
        CFBundleName: AuralKit Demo
        CFBundleDisplayName: AuralKit Demo
        CFBundleIdentifier: com.auralkit.demo.macos
        CFBundleVersion: "1.0.0"
        CFBundleShortVersionString: "1.0.0"
        LSMinimumSystemVersion: "14.0"
        NSMicrophoneUsageDescription: "AuralKit Demo needs microphone access to demonstrate speech-to-text transcription features. Your audio is processed locally on device and not transmitted anywhere."
        NSSpeechRecognitionUsageDescription: "AuralKit Demo uses speech recognition to convert your spoken words into text. This helps demonstrate the framework's capabilities for speech-to-text applications."
        NSPrincipalClass: NSApplication
        NSMainStoryboardFile: Main
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.auralkit.demo.macos
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: true

schemes:
  AuralKitDemo-iOS:
    build:
      targets:
        AuralKitDemo-iOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  AuralKitDemo-macOS:
    build:
      targets:
        AuralKitDemo-macOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release