name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-26

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0'

    - name: Download Metal Toolchain
      run: xcodebuild -downloadComponent MetalToolchain

    - name: Swift build
      run: swift build

    - name: Xcode build Aural
      run: |
        xcodebuild -scheme Aural -configuration Debug -destination "platform=macOS" build
